Add #612 Revisions
decentralised-dataexchange/bb-consent-api pull request #613
Opened 2024-01-10 06:48 UTC by albinpa

2024-01-10 09:31 UTC, georgepadayatti requested changes

2024-01-10 09:31 UTC, georgepadayatti commented on internal/migrate/migrate.go
> +func migrateSchemaNameAndAuthorizedByOtherInRevisionCollection() {
What does this migration function do ?

2024-01-10 09:51 UTC, albinpa commented
Instructions to run bdd test case ,

1.  Make deployable docker image from `main` branch of `bb-consent-api` by executing `make build/docker/deployable` command
2.  Copy `image name` and paste it in `image` fields value under `api` in `test-docker-compose.yaml` file inside test folder in bb-consent-playground
3.  Execute the following commands in `bb-consent-playground`
4.   `make destroy`
5.   `make build-fixtures`
6.   `make build-test`
7.   `make setup-test`
8.   `make run-test`
9.  Make deployable docker image from `feature/612` branch by executing `make build/docker/deployable` command in feature/612 branch
10. Copy image name and paste it in `image` fields value under `api` in `test-docker-compose.yaml` file inside `test` folder in bb-consent-playground
11.  Execute the following commands in `bb-consent-playground`
12.  `make destroy`
13.  `make setup-test`
14.  `make run-test`

2024-01-10 10:12 UTC, georgepadayatti commented
I ran the tests from the `main` branch, and some failed as shown in the screenshot below. But the error is due to the 500 status code. This should not happen, instead, the response returned can contain an older field and fail due to that.

Can you check this ?

![2024-01-10_15-28](https://github.com/decentralised-dataexchange/bb-consent-api/assets/16397960/38658cc8-cc55-4159-b28e-a0d9aea22d8f)

2024-01-10 10:25 UTC, albinpa commented
> I ran the tests from the `main` branch, and some failed as shown in the screenshot below. But the error is due to the 500 status code. This should not happen, instead, the response returned can contain an older field and fail due to that.
> 
> Can you check this ?
> 
> ![2024-01-10_15-28](https://private-user-images.githubusercontent.com/16397960/295529036-38658cc8-cc55-4159-b28e-a0d9aea22d8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODIwOTgsIm5iZiI6MTcwNDg4MTc5OCwicGF0aCI6Ii8xNjM5Nzk2MC8yOTU1MjkwMzYtMzg2NThjYzgtY2M1NS00MTU5LWIyOGUtYTBkOWFlYTIyZDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDEwMTYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MDFkMWU5NjRlNWQ4MjFmYzg3YmEwNDhlZjRmZjJlODE5ODRkMWMzNWE2M2M2MTBiZGIzMjZiYWMxMGE4OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZibC34Lq9RglSB1bnWnKJ7RW2TmbBAoDyzdjXzUu4Os)

The schemaName of data agreement in test data has value DataAgreement,  when trying to fetch revision using schemaName and objectId in delete data agreement in main branch which has schemaName as dataAgreement , the test fails.

2024-01-10 19:35 UTC, georgepadayatti commented
Acceptance criteria for this PR to be merged: https://github.com/decentralised-dataexchange/bb-consent-playground/blob/main/gherkin/features/issue_612/issue_612.feature

Do implement the steps for the validating the above criteria against fix branch.

2024-01-10 19:36 UTC, georgepadayatti requested changes
Acceptance criteria for this PR to be merged: [link](https://github.com/decentralised-dataexchange/bb-consent-playground/blob/main/gherkin/features/issue_612/issue_612.feature)

Do implement the steps for the validating the above criteria against fix branch.

2024-01-10 19:39 UTC, georgepadayatti requested changes

2024-01-10 19:39 UTC, georgepadayatti commented on internal/revision/revisions.go
> +type RevisionForSnapshot struct {
Rename this to `SerialisedSnapshot` or `SerialisedSnapshotForDB`

2024-01-11 09:48 UTC, georgepadayatti commented
Acceptance criteria is met.

![2024-01-11_15-17](https://github.com/decentralised-dataexchange/bb-consent-api/assets/16397960/64aec922-f8b3-4e48-b0fc-d662c90e2e8e)

2024-01-11 09:48 UTC, georgepadayatti commented
Acceptance criteria is met.

![2024-01-11_15-17](https://github.com/decentralised-dataexchange/bb-consent-api/assets/16397960/64aec922-f8b3-4e48-b0fc-d662c90e2e8e)

2024-01-11 09:49 UTC, georgepadayatti approved these changes
Acceptance criteria is met.

![2024-01-11_15-17](https://github.com/decentralised-dataexchange/bb-consent-api/assets/16397960/64aec922-f8b3-4e48-b0fc-d662c90e2e8e)

2024-01-11 09:49 UTC, merged